name: Welcome New Contributors

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thank you for opening your first issue! We appreciate your contribution.'
          pr-message: 'Thank you for opening your first pull request! We appreciate your efforts.'
